### PR TITLE
CI: Update build versions

### PR DESCRIPTION
**Pull request by cookpa**
Remove deprecated actions, build on supported ubuntu

### CODE REVIEW

**Comment by cookpa** [comment]
Hi @stnava, I don't know if this will fix everything but I think the old workflow had some deprecated action versions, it was also asking for a Ubuntu 16.04 runner, which no longer exists - you will need to cancel those jobs

**Comment by cookpa** [comment]
This workflow needs admin approval to run. Looks like the old jobs timed out by themselves

**Comment by stnava** [comment]
@cookpa how do we add "admin approval"?

**Comment by cookpa** [comment]
Is there a button on this page saying something like "approve and run"? If you enable that I should be able to access workflows for future PRs

**Comment by cookpa** [comment]
There it goes, thanks

**Comment by stnava** [comment]
also adding you as admin and transferring ownership to ANTsX

**Pull request closed without merging**
